# Generated by Django 5.0.6 on 2024-06-08 16:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='curso',
        ),
        migrations.RenameField(
            model_name='inscripcion',
            old_name='alumno',
            new_name='jugador',
        ),
        migrations.RenameModel(
            old_name='Alumno',
            new_name='Jugador',
        ),
        migrations.RenameModel(
            old_name='Docente',
            new_name='Paises',
        ),
        migrations.CreateModel(
            name='TipoContratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('turno', models.CharField(max_length=50, verbose_name='Turno')),
                ('cupos', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Cupos')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de finalización')),
                ('jugador', models.ManyToManyField(through='web.Inscripcion', to='web.jugador')),
                ('paises', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.paises')),
            ],
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='tipocontratos',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='web.tipocontratos'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
