# Generated by Django 5.0.6 on 2024-06-28 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('mail', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('fecha_Hora', models.DateField(auto_now_add=True, verbose_name='Fecha de contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('dni', models.IntegerField(unique=True, verbose_name='DNI')),
                ('direccion', models.CharField(verbose_name='Dirección')),
                ('telefono', models.CharField(verbose_name='Teléfono')),
                ('mail', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('estado', models.IntegerField(blank=True, choices=[(1, 'Seleccione'), (2, 'Si'), (3, 'No')], null=True, verbose_name='Pase del club')),
                ('fecha_nacimiento', models.DateField(null=True, verbose_name='Fecha_nacimiento')),
                ('categoria', models.CharField(verbose_name='Categoría')),
                ('posicion', models.IntegerField(choices=[(1, 'Seleccione'), (2, 'Arquero'), (3, 'Defensor Central'), (4, 'Lateral Izquierdo'), (5, 'Lateral Derecho'), (6, 'Mediocampista Central'), (7, 'Mediocampista Izquierdo'), (8, 'Mediocampista Derecho'), (9, 'Delantero')], verbose_name='Posición Contratada: ')),
                ('pais', models.CharField(verbose_name='País')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('dni', models.IntegerField(unique=True, verbose_name='DNI')),
                ('direccion', models.CharField(verbose_name='Dirección')),
                ('telefono', models.CharField(verbose_name='Teléfono')),
                ('mail', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('cuit', models.BigIntegerField(unique=True, verbose_name='CUIT')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='curso',
            name='alumnos',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='docente',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='curso',
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_contratacion', models.DateField(auto_now_add=True, verbose_name='Fecha de contratación')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='TipoContratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('tipo_contrato', models.IntegerField(choices=[(1, 'Seleccione'), (2, 'Amateur'), (3, 'Profesional')], verbose_name='Amateur o Profesional')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('posicion_contratado', models.IntegerField(choices=[(1, 'Seleccione'), (2, 'Arquero'), (3, 'Defensor Central'), (4, 'Lateral Izquierdo'), (5, 'Lateral Derecho'), (6, 'Mediocampista Central'), (7, 'Mediocampista Izquierdo'), (8, 'Mediocampista Derecho'), (9, 'Delantero')], verbose_name='Posición Contratada ')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de finalización')),
                ('clausula', models.CharField(max_length=1000, verbose_name='Clausula')),
                ('monto', models.IntegerField(verbose_name='Monto')),
                ('jugadores', models.ManyToManyField(through='web.Contrato', to='web.jugador')),
                ('representante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.representante')),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='TipoContratos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.tipocontratos'),
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='Docente',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Inscripcion',
        ),
    ]
