# Generated by Django 5.0.6 on 2024-06-21 20:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clausula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Clausula', models.CharField(max_length=1000, unique=True, verbose_name='Clausula')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('dni', models.IntegerField(unique=True, verbose_name='DNI')),
                ('direccion', models.CharField(verbose_name='Dirección')),
                ('telefono', models.CharField(verbose_name='Teléfono')),
                ('mail', models.EmailField(blank=True, max_length=254, verbose_name='E-mail: ')),
                ('estado', models.IntegerField(blank=True, choices=[(1, 'Si'), (2, 'No')], null=True, unique=True, verbose_name='Pase del club')),
                ('categoria', models.CharField(verbose_name='Categoría')),
                ('posicion', models.IntegerField(choices=[(1, 'Arquero'), (2, 'Defensor Central'), (3, 'Lateral Izquierdo'), (4, 'Lateral Derecho'), (5, 'Mediocampista Central'), (6, 'Mediocampista Izquierdo'), (7, 'Mediocampista Derecho'), (8, 'Delantero')], verbose_name='Posición Contratada: ')),
                ('pais', models.CharField(verbose_name='País')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=100, unique=True, verbose_name='País')),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('dni', models.IntegerField(unique=True, verbose_name='DNI')),
                ('direccion', models.CharField(verbose_name='Dirección')),
                ('telefono', models.CharField(verbose_name='Teléfono')),
                ('mail', models.EmailField(blank=True, max_length=254, verbose_name='E-mail: ')),
                ('cuit', models.BigIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(9999999999), django.core.validators.MaxValueValidator(9999999999)], verbose_name='CUIT')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='curso',
            name='alumnos',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='docente',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='curso',
        ),
        migrations.CreateModel(
            name='TipoContratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('tipo_contrato', models.IntegerField(choices=[(1, 'Amateur'), (2, 'Profesional')], verbose_name='Amateur o Profesional')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('posicion_contratado', models.IntegerField(choices=[(1, 'Arquero'), (2, 'Defensor Central'), (3, 'Lateral Izquierdo'), (4, 'Lateral Derecho'), (5, 'Mediocampista Central'), (6, 'Mediocampista Izquierdo'), (7, 'Mediocampista Derecho'), (8, 'Delantero')], verbose_name='Posición Contratada: ')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de finalización')),
                ('clausula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.clausula')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_contratacion', models.DateField(auto_now_add=True, verbose_name='Fecha de contratación')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.jugador')),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.representante')),
                ('TipoContratos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.tipocontratos')),
            ],
            options={
                'db_table': 'contrato',
            },
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='Docente',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Inscripcion',
        ),
    ]
