# Generated by Django 5.0.6 on 2024-06-25 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_clausula_jugador_paises_representante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(1, ' '), (2, 'Si'), (3, 'No')], null=True, verbose_name='Pase del club'),
        ),
        migrations.AlterField(
            model_name='representante',
            name='cuit',
            field=models.IntegerField(unique=True, verbose_name='CUIT'),
        ),
    ]
