# Generated by Django 5.0.6 on 2024-06-08 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_inscripcion_curso_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paises',
            old_name='CUIT',
            new_name='cuit',
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='tipocontratos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.tipocontratos'),
        ),
    ]
