# Generated by Django 5.0.6 on 2024-06-21 20:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_clausula_jugador_paises_representante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='representante',
            name='cuit',
            field=models.BigIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(9999999999), django.core.validators.MaxValueValidator(99999999999)], verbose_name='CUIT'),
        ),
        migrations.AlterField(
            model_name='representante',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
    ]
