# Generated by Django 5.0.6 on 2024-06-09 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_cuit_paises_cuit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paises',
            old_name='cuit',
            new_name='CUIT',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='tipocontratos',
        ),
        migrations.RemoveField(
            model_name='tipocontratos',
            name='jugador',
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='tipo_contrato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.tipocontratos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jugador',
            name='LE',
            field=models.IntegerField(null=True, unique=True, verbose_name='Pase del club'),
        ),
        migrations.AlterField(
            model_name='tipocontratos',
            name='paises',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.paises'),
        ),
        migrations.AlterModelTable(
            name='inscripcion',
            table='inscripcion',
        ),
    ]
