# Generated by Django 5.0.6 on 2024-06-30 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_jugador_estado_alter_jugador_posicion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='fecha_Hora',
            new_name='fecha_hora',
        ),
    ]
