# Generated by Django 5.0.6 on 2024-06-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_jugador_estado_alter_jugador_posicion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='representante',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='tipocontratos',
            name='activo',
            field=models.BooleanField(default=True, null=True, verbose_name='Estado'),
        ),
    ]
