# Generated by Django 5.0.6 on 2024-06-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_jugador_estado_alter_representante_cuit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representante',
            name='cuit',
            field=models.BigIntegerField(unique=True, verbose_name='CUIT'),
        ),
    ]
