# Generated by Django 5.0.6 on 2024-06-25 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_representante_cuit'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='fecha_nacimiento',
            field=models.DateField(null=True, verbose_name='Fecha_nacimiento'),
        ),
    ]
