# Generated by Django 5.0.6 on 2024-06-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_rename_cuit_paises_cuit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepresentanteDeJugadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
