# Generated by Django 5.0.6 on 2024-06-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_jugador_activo_representante_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='representante',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='tipocontratos',
            name='activo',
            field=models.BooleanField(default=True, null=True, verbose_name='Activo'),
        ),
    ]
