# Generated by Django 5.0.6 on 2024-06-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_jugador_activo_alter_representante_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='activo',
            field=models.BooleanField(default=True, null=True, verbose_name='Activo'),
        ),
    ]
