# Generated by Django 5.0.6 on 2024-06-15 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_representantedejugadores'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RepresentanteDeJugadores',
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='tipo_contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.tipocontratos'),
        ),
    ]
