# Generated by Django 5.0.6 on 2024-07-01 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_rename_fecha_hora_contacto_fecha_hora'),
        ('web', '0006_contrato_activo'),
    ]

    operations = [
    ]
