# Generated by Django 5.0.6 on 2024-06-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_delete_representantedejugadores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paises',
            name='CUIT',
        ),
        migrations.RemoveField(
            model_name='tipocontratos',
            name='cupos',
        ),
        migrations.RemoveField(
            model_name='tipocontratos',
            name='turno',
        ),
        migrations.AddField(
            model_name='paises',
            name='Paises',
            field=models.IntegerField(default=1, unique=True, verbose_name='Paises'),
            preserve_default=False,
        ),
    ]
