# Generated by Django 5.0.6 on 2024-06-15 18:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_remove_paises_cuit_remove_tipocontratos_cupos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posicion_Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.CharField(max_length=100, unique=True, verbose_name='Posición')),
            ],
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='tipo_contrato',
        ),
        migrations.RemoveField(
            model_name='paises',
            name='Paises',
        ),
        migrations.RemoveField(
            model_name='paises',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='paises',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='paises',
            name='nombre',
        ),
        migrations.AddField(
            model_name='paises',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='paises',
            name='pais',
            field=models.CharField(default=2, max_length=100, unique=True, verbose_name='País'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipocontratos',
            name='cupos',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Cupos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='posicion_jugador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.posicion_jugador'),
        ),
    ]
