# Generated by Django 5.0.6 on 2024-06-15 18:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_posicion_jugador_remove_inscripcion_tipo_contrato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clausula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clausula', models.CharField(max_length=100, unique=True, verbose_name='Clausula')),
            ],
        ),
        migrations.RemoveField(
            model_name='tipocontratos',
            name='cupos',
        ),
        migrations.RemoveField(
            model_name='tipocontratos',
            name='paises',
        ),
        migrations.AddField(
            model_name='tipocontratos',
            name='tipo_contrato',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Amateur o Profesional'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipocontratos',
            name='clausula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.clausula'),
        ),
    ]
