# Generated by Django 5.0.6 on 2024-06-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_clausula_remove_tipocontratos_cupos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='LE',
        ),
        migrations.AddField(
            model_name='jugador',
            name='Estado',
            field=models.IntegerField(blank=True, choices=[(1, 'Si'), (2, 'No')], null=True, unique=True, verbose_name='Pase del club'),
        ),
    ]
