# Generated by Django 5.0.6 on 2024-07-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_jugador_posicion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='activo',
            field=models.BooleanField(default=True, null=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(1, 'Si'), (2, 'No')], null=True, verbose_name='Pase del club'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='posicion',
            field=models.IntegerField(blank=True, choices=[(1, 'Arquero'), (2, 'Defensor Central'), (3, 'Lateral Izquierdo'), (4, 'Lateral Derecho'), (5, 'Mediocampista Central'), (6, 'Mediocampista Izquierdo'), (7, 'Mediocampista Derecho'), (8, 'Delantero')], null=True, verbose_name='Posición '),
        ),
        migrations.AlterField(
            model_name='tipocontratos',
            name='posicion_contratado',
            field=models.IntegerField(choices=[(1, 'Arquero'), (2, 'Defensor Central'), (3, 'Lateral Izquierdo'), (4, 'Lateral Derecho'), (5, 'Mediocampista Central'), (6, 'Mediocampista Izquierdo'), (7, 'Mediocampista Derecho'), (8, 'Delantero')], verbose_name='Posición Contratada'),
        ),
    ]
