# Generated by Django 5.0.6 on 2024-06-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_remove_jugador_le_jugador_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocontratos',
            name='tipo_contrato',
            field=models.IntegerField(choices=[(1, 'Amateur'), (2, 'Profesional')], verbose_name='Amateur o Profesional'),
        ),
    ]
