# Generated by Django 5.0.6 on 2024-06-18 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_representante_jugador_mail_alter_jugador_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jugador',
            old_name='Estado',
            new_name='estado',
        ),
    ]
