# Generated by Django 5.0.6 on 2024-06-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_rename_estado_jugador_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representante',
            name='cuit',
            field=models.IntegerField(unique=True, verbose_name='CUIT'),
        ),
    ]
